[2024-03-19T11:03:35.413+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:02:00+00:00 [queued]>
[2024-03-19T11:03:35.420+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:02:00+00:00 [queued]>
[2024-03-19T11:03:35.420+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-19T11:03:35.430+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): your_task_id> on 2024-03-19 11:02:00+00:00
[2024-03-19T11:03:35.435+0000] {standard_task_runner.py:60} INFO - Started process 61 to run task
[2024-03-19T11:03:35.438+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Crawler', 'your_task_id', 'scheduled__2024-03-19T11:02:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/new_crawler.py', '--cfg-path', '/tmp/tmp_p5ro9tg']
[2024-03-19T11:03:35.441+0000] {standard_task_runner.py:88} INFO - Job 182: Subtask your_task_id
[2024-03-19T11:03:35.485+0000] {task_command.py:423} INFO - Running <TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:02:00+00:00 [running]> on host 26a0b219297f
[2024-03-19T11:03:35.559+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Xirano' AIRFLOW_CTX_DAG_ID='Crawler' AIRFLOW_CTX_TASK_ID='your_task_id' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T11:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T11:02:00+00:00'
[2024-03-19T11:04:25.832+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:00:54.947518.
[2024-03-19T11:04:30.867+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:00:59.983106.
[2024-03-19T11:04:30.868+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2024-03-19T11:04:30.869+0000] {process_utils.py:131} INFO - Sending 15 to group 61. PIDs of all processes in the group: [61]
[2024-03-19T11:04:30.870+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 61
[2024-03-19T11:04:30.870+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19T11:04:30.871+0000] {logging_mixin.py:188} INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
[2024-03-19T11:04:30.871+0000] {logging_mixin.py:188} INFO -  the error acuire in crawl data from TSETMS Task received SIGTERM signal
[2024-03-19T11:04:30.871+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-19T11:04:30.882+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Crawler, task_id=your_task_id, execution_date=20240319T110200, start_date=20240319T110335, end_date=20240319T110430
[2024-03-19T11:04:30.901+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=61, status='terminated', exitcode=0, started='11:03:34') (61) terminated with exit code 0
