[2024-03-19T11:10:01.740+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:09:00+00:00 [queued]>
[2024-03-19T11:10:01.747+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:09:00+00:00 [queued]>
[2024-03-19T11:10:01.748+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-19T11:10:01.758+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): your_task_id> on 2024-03-19 11:09:00+00:00
[2024-03-19T11:10:01.765+0000] {standard_task_runner.py:60} INFO - Started process 176 to run task
[2024-03-19T11:10:01.769+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Crawler', 'your_task_id', 'scheduled__2024-03-19T11:09:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/new_crawler.py', '--cfg-path', '/tmp/tmp5ji2hvtn']
[2024-03-19T11:10:01.772+0000] {standard_task_runner.py:88} INFO - Job 189: Subtask your_task_id
[2024-03-19T11:10:01.817+0000] {task_command.py:423} INFO - Running <TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:09:00+00:00 [running]> on host 26a0b219297f
[2024-03-19T11:10:01.889+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Xirano' AIRFLOW_CTX_DAG_ID='Crawler' AIRFLOW_CTX_TASK_ID='your_task_id' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T11:09:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T11:09:00+00:00'
[2024-03-19T11:10:52.119+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:00:51.308677.
[2024-03-19T11:10:57.155+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:00:56.345207.
[2024-03-19T11:10:57.156+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2024-03-19T11:10:57.158+0000] {process_utils.py:131} INFO - Sending 15 to group 176. PIDs of all processes in the group: [176]
[2024-03-19T11:10:57.159+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 176
[2024-03-19T11:10:57.159+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19T11:10:57.160+0000] {logging_mixin.py:188} INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
[2024-03-19T11:10:57.160+0000] {logging_mixin.py:188} INFO -  the error acuire in crawl data from TSETMS Task received SIGTERM signal
[2024-03-19T11:10:57.160+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-19T11:10:57.171+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Crawler, task_id=your_task_id, execution_date=20240319T110900, start_date=20240319T111001, end_date=20240319T111057
[2024-03-19T11:10:57.189+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=176, status='terminated', exitcode=0, started='11:10:00') (176) terminated with exit code 0
