[2024-03-19T11:08:01.548+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:07:00+00:00 [queued]>
[2024-03-19T11:08:01.554+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:07:00+00:00 [queued]>
[2024-03-19T11:08:01.555+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-19T11:08:01.564+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): your_task_id> on 2024-03-19 11:07:00+00:00
[2024-03-19T11:08:01.570+0000] {standard_task_runner.py:60} INFO - Started process 139 to run task
[2024-03-19T11:08:01.574+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Crawler', 'your_task_id', 'scheduled__2024-03-19T11:07:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/new_crawler.py', '--cfg-path', '/tmp/tmpvbvs2k09']
[2024-03-19T11:08:01.577+0000] {standard_task_runner.py:88} INFO - Job 187: Subtask your_task_id
[2024-03-19T11:08:01.621+0000] {task_command.py:423} INFO - Running <TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:07:00+00:00 [running]> on host 26a0b219297f
[2024-03-19T11:08:01.693+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Xirano' AIRFLOW_CTX_DAG_ID='Crawler' AIRFLOW_CTX_TASK_ID='your_task_id' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T11:07:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T11:07:00+00:00'
[2024-03-19T11:08:51.933+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:00:51.367921.
[2024-03-19T11:08:56.971+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:00:56.406262.
[2024-03-19T11:08:56.972+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2024-03-19T11:08:56.974+0000] {process_utils.py:131} INFO - Sending 15 to group 139. PIDs of all processes in the group: [139]
[2024-03-19T11:08:56.974+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 139
[2024-03-19T11:08:56.975+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19T11:08:56.975+0000] {logging_mixin.py:188} INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
[2024-03-19T11:08:56.976+0000] {logging_mixin.py:188} INFO -  the error acuire in crawl data from TSETMS Task received SIGTERM signal
[2024-03-19T11:08:56.976+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-19T11:08:56.985+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Crawler, task_id=your_task_id, execution_date=20240319T110700, start_date=20240319T110801, end_date=20240319T110856
[2024-03-19T11:08:57.005+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=139, status='terminated', exitcode=0, started='11:08:00') (139) terminated with exit code 0
