[2024-03-19T11:06:01.181+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:05:00+00:00 [queued]>
[2024-03-19T11:06:01.189+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:05:00+00:00 [queued]>
[2024-03-19T11:06:01.190+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-19T11:06:01.201+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): your_task_id> on 2024-03-19 11:05:00+00:00
[2024-03-19T11:06:01.209+0000] {standard_task_runner.py:60} INFO - Started process 109 to run task
[2024-03-19T11:06:01.213+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Crawler', 'your_task_id', 'scheduled__2024-03-19T11:05:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/new_crawler.py', '--cfg-path', '/tmp/tmp8f32cuhk']
[2024-03-19T11:06:01.216+0000] {standard_task_runner.py:88} INFO - Job 185: Subtask your_task_id
[2024-03-19T11:06:01.264+0000] {task_command.py:423} INFO - Running <TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:05:00+00:00 [running]> on host 26a0b219297f
[2024-03-19T11:06:01.346+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Xirano' AIRFLOW_CTX_DAG_ID='Crawler' AIRFLOW_CTX_TASK_ID='your_task_id' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T11:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T11:05:00+00:00'
[2024-03-19T11:06:51.583+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:00:51.412700.
[2024-03-19T11:06:56.623+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:00:56.452607.
[2024-03-19T11:06:56.624+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2024-03-19T11:06:56.626+0000] {process_utils.py:131} INFO - Sending 15 to group 109. PIDs of all processes in the group: [109]
[2024-03-19T11:06:56.627+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 109
[2024-03-19T11:06:56.627+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19T11:06:56.628+0000] {logging_mixin.py:188} INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
[2024-03-19T11:06:56.628+0000] {logging_mixin.py:188} INFO -  the error acuire in crawl data from TSETMS Task received SIGTERM signal
[2024-03-19T11:06:56.628+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-19T11:06:56.641+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Crawler, task_id=your_task_id, execution_date=20240319T110500, start_date=20240319T110601, end_date=20240319T110656
[2024-03-19T11:06:56.683+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=109, status='terminated', exitcode=0, started='11:06:00') (109) terminated with exit code 0
